### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by 89luca89** [89luca89/Gedit-External-Tools-SaveSession#1]
![photo_2016-12-10_19-10-49](https://cloud.githubusercontent.com/assets/598882/21075206/8240a82c-bf0c-11e6-94ce-c452ca17e9f7.jpg)
![photo_2016-12-10_19-11-02](https://cloud.githubusercontent.com/assets/598882/21075207/824812e2-bf0c-11e6-9b8f-60b02b36ca9c.jpg)
![photo_2016-12-10_19-11-08](https://cloud.githubusercontent.com/assets/598882/21075208/824e86cc-bf0c-11e6-858c-80ebe9ebc447.jpg)
![photo_2016-12-10_19-11-13](https://cloud.githubusercontent.com/assets/598882/21075209/8251fac8-bf0c-11e6-8af3-d503c1962d4c.jpg)
![photo_2016-12-10_19-11-15](https://cloud.githubusercontent.com/assets/598882/21075210/8256d778-bf0c-11e6-8146-a2235351639f.jpg)
![photo_2016-12-10_19-11-18](https://cloud.githubusercontent.com/assets/598882/21075211/825b7d64-bf0c-11e6-8308-0ee638f4d52a.jpg)
![photo_2016-12-10_19-11-22](https://cloud.githubusercontent.com/assets/598882/21075212/82629766-bf0c-11e6-9689-a30716c968a8.jpg)

**Comment by rogelio-meza-t** [comment]
Which icon set (for gnome) are you using? Because for me using the default dark theme in gedit, the left panel gets light brown icons

**Comment by 89luca89** [comment]
@rogelio-meza-t it was Paper, but I reverted back to adwaita, and now are light brown like yours :)
